//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiApp1.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiApp1.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Âm thanh.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghe nội dung giới thiệu bằng âm thanh.
        /// </summary>
        public static string AudioDescription {
            get {
                return ResourceManager.GetString("AudioDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuyết minh tự động.
        /// </summary>
        public static string AutoAudio {
            get {
                return ResourceManager.GetString("AutoAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuyết minh tự động đa ngôn ngữ.
        /// </summary>
        public static string AutoDescription {
            get {
                return ResourceManager.GetString("AutoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuyết Minh Tự Động.
        /// </summary>
        public static string AutoGuide {
            get {
                return ResourceManager.GetString("AutoGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động phát thuyết minh khi vào vùng.
        /// </summary>
        public static string AutoPlay {
            get {
                return ResourceManager.GetString("AutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động phát thuyết minh khi vào vùng.
        /// </summary>
        public static string AutoPlayDesc {
            get {
                return ResourceManager.GetString("AutoPlayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngôn ngữ.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã vào khu vực.
        /// </summary>
        public static string EnterArea {
            get {
                return ResourceManager.GetString("EnterArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã rời khỏi khu vực.
        /// </summary>
        public static string ExitArea {
            get {
                return ResourceManager.GetString("ExitArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phố Ẩm Thực.
        /// </summary>
        public static string FoodStreet {
            get {
                return ResourceManager.GetString("FoodStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vĩ độ.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghe ngay.
        /// </summary>
        public static string ListenNow {
            get {
                return ResourceManager.GetString("ListenNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        public static string ListTitle {
            get {
                return ResourceManager.GetString("ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinh độ.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản Đồ.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        public static string MapTitle {
            get {
                return ResourceManager.GetString("MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bán kính.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khôi phục.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn khôi phục cài đặt mặc định?.
        /// </summary>
        public static string ResetConfirm {
            get {
                return ResourceManager.GetString("ResetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset về mặc định.
        /// </summary>
        public static string ResetDefault {
            get {
                return ResourceManager.GetString("ResetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phát.
        /// </summary>
        public static string Speak {
            get {
                return ResourceManager.GetString("Speak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tốc độ giọng nói.
        /// </summary>
        public static string SpeechSpeed {
            get {
                return ResourceManager.GetString("SpeechSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dừng.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ hỗ trợ.
        /// </summary>
        public static string SupportedLanguage {
            get {
                return ResourceManager.GetString("SupportedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món Việt.
        /// </summary>
        public static string VietnamFood {
            get {
                return ResourceManager.GetString("VietnamFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Âm lượng.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
